### ISSUE TITLE
Integrate Alerting with the Notification plugin

### ISSUE THREAD

**Issue by praveensameneni** [opensearch-project/alerting#105]
The Alerting plugin plans to integrate with the Notification plugin in 2.0. This will remove the `notification` subproject logic and will delegate to the Notification plugin for managing things like destination configurations and publishing the messages for the  Notification Actions that Monitors have today.

**Comment by qreshi** [comment]
With this integration comes some breaking changes, here is what we are expecting to happen:

### For 2.0
#### Breaking Changes
* All Destination API will be removed (except perhaps the Get Destinations API so that users can see what Destinations have yet to migrate, UI can also show a read-only state using this API, etc.), any CRUD operations regarding Notification Channels will have to be done through the Notification plugin API
* Notification jar logic in Alerting will be removed (this is mostly breaking for something like ISM which will have to use the Notification plugin to publish now which is expected)

#### Non-Breaking but worth noting
* A background process will be running to migrate any Destinations to Notification Channels on the users behalf (deleting Destinations that have successfully migrated)
* The Monitor execution will automatically use the Notification Channel for Action execution if it was migrated, falling back to Destinations (via an internal passthrough API) in the cases where migration has not yet happened or failed
* Any Destination specific plugin settings will be deprecated but not removed and have Notification versions which will inherit from the Alerting setting value (to ensure a smooth transition)
  * This includes the keystore settings being used for Email Destinations (we’ll be keeping both for now, Notifications’ takes precedence and users will need to make sure they’re moving over to the Notification namespace during 2.x)


### For 3.0
#### Breaking Changes
* The background process for Destination -> Notification Channel migration will be removed (we don’t expect to handle migrating from OS 1.x -> 3.0 so the user will need to go through 2.x -> 3.0 and ensure their Destinations have migrated prior to upgrade)
* Monitor runner fallback can be removed as we don’t expect to have Destinations anymore
* Get Destinations API will be removed
* Alerting Destination keystore settings (for email) will be removed
 
#### Non-Breaking but worth noting
* All other Alerting Destination settings will be removed (these are non-breaking because in 2.x the Notification versions of these settings are taking precedence anyway)

**Comment by dblock** [comment]
I believe this was done, @qreshi correct me if I am wrong? Closing.

**Comment by qreshi** [comment]
Not done yet :)

**Comment by dblock** [comment]
What's left?
