### ISSUE TITLE
Remove HOST_DENY_LIST usage and migrate it to notification plugin

### ISSUE THREAD

**Issue by dbbaughe** [opensearch-project/alerting#134]
https://github.com/opensearch-project/notifications/issues/247

**Comment by qreshi** [comment]
Notifications has the host deny list setting `opensearch.notifications.core.http.host_deny_list` (which uses the Alerting setting `plugins.destination.host.deny_list` and subsequently the legacy setting `opendistro.destination.host.deny_list` as fallbacks). If none of the mentioned settings are already set, the default is an empty list.

These changes were made in https://github.com/opensearch-project/notifications/pull/424.

The Alerting versions of the settings are now deprecated and the plan is to remove them in `3.0`. We're keeping them in `2.x` so they can act as fallback settings to ensure smooth transitions for upgrading users since the Alerting setting was the only "host deny list" option for Destination configs up until now.
