### ISSUE TITLE
Replace opendistro-alerting-1.13.1.0.zip with an external download

### ISSUE THREAD

**Issue by dblock** [opensearch-project/alerting#350]
Coming from https://github.com/opensearch-project/opensearch-build/issues/1750, replace the checked in alerting/alerting/src/test/resources/bwc/alerting/1.13.1.0/opendistro-alerting-1.13.1.0.zip with an external download during bwc test if it's still used.

**Comment by lezzago** [comment]
This would also need change the [notification zips](https://github.com/opensearch-project/alerting/tree/main/alerting/src/test/resources) to be retrieved for an external download. This is going to be difficult currently since these zips will need to be the latest versions of the notification zips as the version gets bumped over time.

**Comment by dblock** [comment]
@lezzago Is this more complicated than https://github.com/opensearch-project/cross-cluster-replication/pull/366?

**Comment by qreshi** [comment]
PR has been merged and backported to `2.0` branch as well. Closing.
