### ISSUE TITLE
[BUG] Support deletion of queries from custom query index

### ISSUE THREAD

**Issue by eirsep** [opensearch-project/alerting#581]
Related to #522

When deleting a monitor, the corresponding query index should be cleaned up. With introduction of custom query index, we need to support deletion of queries from the appropriate query index by checking datasource config of monitor

**Comment by getsaurabh02** [comment]
This is basically a two step cleanup process:

1. **Clean Query Documents from Query Index for Detector being deleted** : All the queries from different monitor which are  for the same log-type end up being part of the same Rule Index. Each query is persisted as a single document with ID as the key identifier of owner. Once the monitor is deleted, it should clean up the queries it added to the query index


2. **Cleanup the Query Index if there are no active monitors** : The last monitor which is cleaning up its queries should clean up the rule index, since it will be an empty index.
