### ISSUE TITLE
After Insert Trigger request

### ISSUE THREAD

**Issue by sankar2389** [opensearch-project/alerting#767]
**Is your feature request related to a problem?**
Hi I tried to find perfect alternate method of after insert trigger like mysql in opensearch.
https://www.javatpoint.com/mysql-after-insert-trigger

Also checked the document level monitoring - (https://opensearch.org/docs/latest/monitoring-plugins/alerting/monitors/#per-document-monitors). But couldn't able to find any suitable alternatives.

**What alternatives have you considered?**
For now I'm considering to try using the cloudwatch logs of opensearch insert, update happenings & try an invocation using the logs.

**Comment by lezzago** [comment]
This is currently out of scope for the Alerting plugin due to scale of data volume and big performance implications to execute the monitor whenever a new record is inserted in the index. Document level monitors will be close to that, but can only get executed every minute and will ensure it will only looks at the newly indexed data.
