### ISSUE TITLE
[BUG] message template {{ctx.monitor._id}} not available

### ISSUE THREAD

**Issue by aditjind** [opensearch-project/alerting#84]
<a href="https://github.com/amrzteb"><img src="https://avatars.githubusercontent.com/u/31942129?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amrzteb](https://github.com/amrzteb)**
_Thursday Dec 03, 2020 at 06:19 GMT_
_Originally opened as https://github.com/opendistro-for-elasticsearch/alerting/issues/315_

----

**Describe the bug**
message template {{ctx.monitor._id}} not available

**Comment by aditjind** [comment]
Hi @amrzteb 

The variable `ctx.monitor._id` is available whenever the monitor is running on schedule. The only time the variable is unavailable is when we are testing the functionality of sending the alerts. This is an internal implementation detail. Please let us know if you are facing the problem of this variable being unavailable in monitors which are running on schedule.

**Comment by aditjind** [comment]
This implementation detail is while testing the web-hook we provide the monitor as an input and that is not fetched from the indexed document. We should keep it this way since we have other workflows in our implementation where we test the monitor using the `TEMP MONITOR` while running the query on the create Monitor page. This monitor is not indexed and _id won't be available for these types of monitors. Hope this resolves your query. Feel free to open if you need any more help on this issue.

**Comment by qreshi** [comment]
Closing this as it seems like a non-issue. `ctx.monitor._id` will be available if it's being used with a scheduled Monitor. If a Monitor is ran in-line via the [execute API](https://opensearch.org/docs/latest/monitoring-plugins/alerting/api/#request-7) (such as what is done internally when the "Send test message" is called during Monitor creation from the frontend) then there will be no Monitor ID since the Monitor job hasn't been indexed.

Feel free to re-open the issue if there are any concerns.
